# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Secluso, Inc.
# Additional terms apply; see the NOTICE file in the repository root.

[main]
plugins=keyfile
dhcp=dnsmasq
dns=dnsmasq

[keyfile]
unmanaged-devices=none

# make wlan0 a managed device
[device]
match-device=interface-name:wlan0
managed=true
