# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Secluso, Inc.
# Additional terms apply; see the NOTICE file in the repository root.

# Default layer.conf provided by bitbake-layers

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "secluso-os"
BBFILE_PATTERN_secluso-os = "^${LAYERDIR}/"
BBFILE_PRIORITY_secluso-os = "6"

LAYERDEPENDS_secluso-os = "core"
LAYERSERIES_COMPAT_secluso-os = "whinlatter"